[cmds] Reorganize ELKS command installation (#466)
* [cmds] Reorganize ELKS command installation

* Fix sed quotes

* Use /bin/bash in Makefile to support curly brace expansion

diff --git a/elkscmd/Makefile b/elkscmd/Makefile
--- a/elkscmd/Makefile
+++ b/elkscmd/Makefile
@@ -14,6 +14,8 @@ include $(BASEDIR)/Make.defs
 
 # All subdirectories to build & clean
 
+# TODO: broken command compilations
+# byacc elvis screen m4 xvi
 SUBDIRS =       \
 	ash         \
 	bc          \
@@ -36,87 +38,101 @@ SUBDIRS =       \
 	test        \
 	# EOL
 
-# TODO: fix broken command compilations
-# misc_utils/lpfilter.c
-#SUBDIRS += byacc elvis screen xvi
+# Application Package List
+PACKAGE=$(ELKSCMD_DIR)/Applications
+# Install destination
+DESTDIR=$(TOPDIR)/target
+TAGS=
+# Old-style installation
+INSTDIRS=
 
-# Directories to install
-
-INSTDIRS = \
-	inet \
-	# EOL
-
-ifeq ($(CONFIG_APP_ASH), y)
-INSTDIRS += ash
+ifdef CONFIG_APP_ASH
+	TAGS += :ash|
 endif
 
-ifeq ($(CONFIG_APP_BC), y)
-INSTDIRS += bc
-endif
-
-ifeq ($(CONFIG_APP_BUSYELKS), y)
-INSTDIRS += busyelks
+ifdef CONFIG_APP_BUSYELKS
+	TAGS += :busyelks|
 endif
 
 ifdef CONFIG_APP_DISK_UTILS
-INSTDIRS += disk_utils
+	TAGS += :diskutil|
+	ifeq ($(CONFIG_APP_DISK_UTILS), y)
+		TAGS += :be-diskutil|
+	endif
 endif
 
 ifdef CONFIG_APP_FILE_UTILS
-INSTDIRS += file_utils
+	TAGS += :fileutil|
+	ifeq ($(CONFIG_APP_FILE_UTILS), y)
+		TAGS += :be-fileutil|
+	endif
 endif
 
-ifeq ($(CONFIG_APP_LEVEE), y)
-INSTDIRS += levee
+ifdef CONFIG_APP_LEVEE
+	TAGS += :levee|
 endif
 
-ifeq ($(CONFIG_APP_KTCP), y)
-INSTDIRS += ktcp
+ifdef CONFIG_APP_KTCP
+	TAGS += :net|
 endif
 
 ifdef CONFIG_APP_MINIX1
-INSTDIRS += minix1
+	TAGS += :minix1|
+	ifeq ($(CONFIG_APP_MINIX1), y)
+		TAGS += :be-minix1|
+	endif
 endif
 
-ifeq ($(CONFIG_APP_MINIX2), y)
-INSTDIRS += minix2
+ifdef CONFIG_APP_MINIX2
+	TAGS += :minix2|
 endif
 
 ifdef CONFIG_APP_MINIX3
-INSTDIRS += minix3
+	TAGS += :minix3|
+	ifeq ($(CONFIG_APP_MINIX3), y)
+		TAGS += :be-minix3|
+	endif
 endif
 
-ifeq ($(CONFIG_APP_MTOOLS), y)
-INSTDIRS += mtools
+ifdef CONFIG_APP_MTOOLS
+	TAGS += :mtools|
 endif
 
 ifdef CONFIG_APP_MISC_UTILS
-INSTDIRS += misc_utils
+	TAGS += :miscutil|
+	ifeq ($(CONFIG_APP_MISC_UTILS), y)
+		TAGS += :be-miscutil|
+	endif
 endif
 
-ifeq ($(CONFIG_APP_NANOX), y)
-INSTDIRS += nano-X
+ifdef CONFIG_APP_NANOX
+	TAGS += :nanox|
 endif
 
-ifeq ($(CONFIG_APP_PREMS), y)
-INSTDIRS += prems
+ifdef CONFIG_APP_OTHER
+	TAGS += :other|
 endif
 
-ifeq ($(CONFIG_APP_SASH), y)
-INSTDIRS += sash
+ifdef CONFIG_APP_SASH
+	TAGS += :sash|
 endif
 
-ifeq ($(CONFIG_APP_SH_UTILS), y)
-INSTDIRS += sh_utils
+ifdef CONFIG_APP_SH_UTILS
+	TAGS += :shutil|
+	ifeq ($(CONFIG_APP_SH_UTILS), y)
+		TAGS += :be-shutil|
+	endif
 endif
 
-ifeq ($(CONFIG_APP_SYS_UTILS), y)
-INSTDIRS += sys_utils
+ifdef CONFIG_APP_SYS_UTILS
+	TAGS += :sysutil|
 endif
 
 ifdef CONFIG_APP_TEST
-INSTDIRS += test
+	INSTDIRS += test
 endif
+
+TAGS += :end
 
 ###############################################################################
 #
@@ -129,8 +145,36 @@ all:
 	then echo -e "\n*** ERROR: You must configure ELKS first ***\n" >&2; exit 1; fi
 	for DIR in $(SUBDIRS); do $(MAKE) -C $$DIR all || exit 1; done
 
+# use bash instead of /bin/sh for curly brace expansion
+SHELL=/bin/bash
 install:
-	for i in $(INSTDIRS); do $(MAKE) -C $$i install || exit 1; done
+	@echo "TAGS=$(TAGS)" | tr -d ' '
+	awk /`echo "$(TAGS)" | tr -d ' '`/{print} $(PACKAGE) | sed '/^#/d' > Filelist
+	@while IFS= read -r line; \
+	do \
+		file=`echo $$line | cut -d" " -f 1`; \
+		dir=`echo $$line | cut -d" " -f 2`; \
+		if [ "$${dir:0:2}" == "::" ]; \
+		then \
+			instdir=$${dir:2}; \
+		else \
+			instdir=bin; \
+		fi; \
+		echo install $$file to $$instdir; \
+		if [ ! -e $$file ]; \
+		then \
+			echo "File specified in $(PACKAGE) not found: $$file"; \
+			exit 1; \
+		else \
+			[ ! -d $$file ] && mkdir -p $$(dirname $(DESTDIR)/$$instdir); \
+			[ -f $$file ] && $(INSTALL) $$file $(DESTDIR)/$$instdir; \
+		fi \
+	done < Filelist
+	rm Filelist
+ifdef CONFIG_APP_BUSYELKS
+	$(MAKE) -C busyelks links
+endif
+	for DIR in $(INSTDIRS); do $(MAKE) -C $$DIR clean || exit 1; done
 
 clean:
 	for DIR in $(SUBDIRS); do $(MAKE) -C $$DIR clean || exit 1; done
