elkscmd: Makefile fixes

diff --git a/elkscmd/Makefile b/elkscmd/Makefile
--- a/elkscmd/Makefile
+++ b/elkscmd/Makefile
@@ -40,8 +40,8 @@ KHELPER 	= $(MINIX_BOOT)/minix_elks.bin
 # Compile everything.
 
 all:
-	@test -e $(ELKS_DIR)/include/linuxmt/config.h && \
-		echo -e "\n*** ERROR: You must build the ELKS kernel first ***\n" >&2 && exit 1
+	if [ ! -e $(ELKS_DIR)/include/linuxmt/config.h ]; \
+	then echo -e "\n*** ERROR: You must build the ELKS kernel first ***\n" >&2; exit 1; fi
 	@for i in $(DIRS); do make -C $$i all ; done
 
 clean:
@@ -140,7 +140,8 @@ boot_blocks: $(FD_BSECT) $(KHELPER)
 _build_bootable_target: _build_target kernel_image boot_blocks
 	mkdir -p $(TARGET_MNT)/boot
 	cp $(ELKS_DIR)/arch/i86/boot/Image $(TARGET_MNT)/boot/linux
-	cp $(KHELPER) $(TARGET_MNT)/boot/boot
+	-cp $(KHELPER) $(TARGET_MNT)/boot/boot || \
+	echo -e "\n\n *** WARNING: Failed to copy boot binary ***\n\n"
 	umount $(TARGET_FS)
 	dd if=$(FD_BSECT) of=$(TARGET_FS) bs=512 count=2 conv=notrunc 2>/dev/null
 
@@ -150,12 +151,14 @@ _build_nonbootable_target: _build_target
 _build_target: all banner check_id _populate_target
 
 _populate_target: _mount_target
-	for i in $(DIRS); do make -C $$i $(TARGET_RFS)||exit 1; done >/dev/null
+	-for i in $(DIRS); do make -C $$i $(TARGET_RFS); done >/dev/null
 	$(ELKSCMD_DIR)/tools/ver.pl $(ELKS_DIR)/Makefile > $(TARGET_MNT)/etc/issue
 	[ "$(INSTALL_KTCP)" = "yes" ] && \
 	cp -p $(ELKSNET_DIR)/ktcp/ktcp $(TARGET_MNT)/bin || true
 
 _mount_target:
+	@if [ "$(shell id -u)" != "0" ]; \
+	then echo -e "\n\n *** Only root can build disk images *** \n\n"; exit 1; fi
 	umount $(TARGET_FS) >/dev/null 2>&1 || true
 	dd if=/dev/zero of=$(TARGET_FS) bs=1024 count=$(TARGET_BLKS) 2>/dev/null
 	$(MKFS) $(MKFS_OPTS) $(TARGET_FS) $(TARGET_BLKS) >/dev/null
@@ -178,6 +181,8 @@ check_id:
 	fi
 
 full3:
+	@if [ "$(shell id -u)" != "0" ]; \
+	then echo -e "\n\n *** Only root can build disk images *** \n\n"; exit 1; fi
 	@$(MAKE) _build_bootable_target \
 		TARGET_FS=$(FULL3_TARGET_FS) \
 		TARGET_RFS=rfs \
@@ -185,6 +190,8 @@ full3:
 		INSTALL_KTCP=yes
 
 full5:
+	@if [ "$(shell id -u)" != "0" ]; \
+	then echo -e "\n\n *** Only root can build disk images *** \n\n"; exit 1; fi
 	@$(MAKE) _build_bootable_target \
 		TARGET_FS=$(FULL5_TARGET_FS) \
 		TARGET_RFS=rfs \
@@ -192,12 +199,16 @@ full5:
 		INSTALL_KTCP=yes
 
 comb:
+	@if [ "$(shell id -u)" != "0" ]; \
+	then echo -e "\n\n *** Only root can build disk images *** \n\n"; exit 1; fi
 	@$(MAKE) _build_bootable_target \
 		TARGET_FS=$(COMB_TARGET_FS) \
 		TARGET_RFS=min_rfs \
 		TARGET_BLKS=$(COMB_TARGET_BLKS)
 
 comb_net:
+	@if [ "$(shell id -u)" != "0" ]; \
+	then echo -e "\n\n *** Only root can build disk images *** \n\n"; exit 1; fi
 	@$(MAKE) _build_bootable_target \
 		TARGET_FS=$(ROOT_NET_TARGET_FS) \
 		TARGET_RFS=net_rfs \
@@ -209,6 +220,8 @@ boot: $(ELKS_DIR)/arch/i86/boot/Image
 	
 
 root:
+	@if [ "$(shell id -u)" != "0" ]; \
+	then echo -e "\n\n *** Only root can build disk images *** \n\n"; exit 1; fi
 	@$(MAKE) _build_nonbootable_target \
 		TARGET_FS=$(ROOT_TARGET_FS) \
 		TARGET_RFS=min_rfs \
