Option changes to makeboot, update to sys

diff --git a/elkscmd/rootfs_template/bin/sys b/elkscmd/rootfs_template/bin/sys
--- a/elkscmd/rootfs_template/bin/sys
+++ b/elkscmd/rootfs_template/bin/sys
@@ -5,9 +5,9 @@
 usage()
 {
 	echo "Usage: sys [-3][-M][-F] /dev/{fd0,fd1,hda1,hda2,etc}"
-	echo "	-3 will transfer minimal (360k) system"
-	echo "	-M will transfer boot MBR to /dev/hd[a-d][1-4]"
-	echo "	-F required for flat non-MBR /dev/hd[a-d]"
+	echo "	-3  Build minimal (360k) system"
+	echo "	-M  add MBR to target device"
+	echo "	-F  required for flat non-MBR /dev/hd[a-d]"
 	exit 1
 }
 
@@ -26,7 +26,9 @@ create_dev_dir()
 	mknod $MNT/dev/null	c 1 3
 	mknod $MNT/dev/zero	c 1 5
 	mknod $MNT/dev/tcpdev	c 8 0
-	mknod $MNT/dev/eth	c 9 0
+	mknod $MNT/dev/ne2k	c 9 0
+	mknod $MNT/dev/wd8003	c 9 1
+	mknod $MNT/dev/3c509	c 9 2
 	mknod $MNT/dev/ptyp0	c 2 8
 	mknod $MNT/dev/ttyp0	c 4 8
 	mknod $MNT/dev/tty1	c 4 0
@@ -115,22 +117,19 @@ copy_etc_files()
 # sys script starts here
 MNT=/tmp/mnt
 small=0
-
-if test "$1" = "-M"; then shift; arg=-M; fi
-if test "$1" = "-F"; then shift; arg=-F; fi
+arg=-s
+if test "$1" = "-M"; then shift; arg="-M -s"; fi
+if test "$1" = "-F"; then shift; arg="-F -s"; fi
 if test "$1" = "-3"; then shift; small=1; fi
 if test "$#" -lt 1; then usage; fi
 
 # returns fstype, 1=MINIX, 2=FAT
 makeboot $arg $1
 FSTYPE=$?
+if test "$FSTYPE" = "255"; then exit 1; fi;
 
 mkdir -p $MNT
-case "$FSTYPE" in
-1) mount $1 $MNT || exit 1 ;;
-2) mount -t msdos $1 $MNT || exit 1 ;;
-*) exit 1 ;;
-esac
+mount $1 $MNT 
 
 # if MINIX, create /dev entries
 if test "$FSTYPE" = "1"; then create_dev_dir; fi
